markdown: rdiscount
permalink: /:title/
url: laukey.github.io
cname: www.laukey.com
highlighter: pygments
name: laukey
description: laukey | fighting and doing.
author: laukey
email: laukeygood@gmail.com
duoshuo: fdgdfg
hub: laukey
safe: true
paginate: 100
about: "laukey"
