markdown: rdiscount
permalink: /:title/
url: laukey.github.io
highlighter: pygments
name: laukey
description: laukey | fighting and doing.
author: laukey
email: dodirectthing@gmail.com
duoshuo: weibo.com/2280323751
hub: laukey
safe: true
paginate: 100
about: "laukey"
